# Generated by Django 3.1 on 2020-09-09 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='user',
            new_name='watch_user',
        ),
    ]
