# Generated by Django 3.1 on 2020-09-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_listing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.URLField(default='https://upload.wikimedia.org/wikipedia/commons/a/ac/No_image_available.svg'),
        ),
    ]
